// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 16
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){


var ya=this,za=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Aa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ba=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ca=function(a){if(null==a)return String(a);var b=Ba.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Da=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ma=function(a){if(!a||"object"!=Ca(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Da(a,"constructor")&&!Da(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Da(a,b)},Fa=function(a,b){var c=b||("array"==Ca(a)?[]:{}),d;for(d in a)if(Da(a,d)){var e=a[d];"array"==Ca(e)?("array"!=Ca(c[d])&&(c[d]=[]),c[d]=Fa(e,c[d])):ma(e)?(ma(c[d])||(c[d]={}),c[d]=Fa(e,c[d])):c[d]=e}return c};var qa=null,Ga=Math.random(),Ha=null,Ia=null,Ja={};var Ka,La,Ma,Na,Oa,Pa,Qa,Sa,Ua,Va,Wa,Xa,Q,Ya,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,jb,lb,mb,nb,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Cb,Db,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,R,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,hd,id,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,
ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se;
(function(){var a=function(a){return{toString:function(){return a}}};Ka=a("");La=a("0");Ma="";Na=a("");Oa=a("");Pa=a("");Qa=a("");Sa=a("");Ua=a("1");Va=a("4");Wa=a("");Xa=a("5");Q=a("6");Ya=a("");Za=a("7");$a=a("");
ab=a("");bb=a("");cb=a("");db=a("");eb=a("");fb=a("");gb=a("");hb=a("");jb=a("");lb=a("");mb=a("");nb=a("");ob=a("");pb=
a("");qb=a("");rb=a("8");sb=a("");tb=a("");ub=a("");vb=a("");wb=a("9");xb=a("10");yb=a("");zb=a("");Ab=a("");Cb=a("");Db=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");
Jb=a("");Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");Rb=a("11");Sb=a("");Tb=a("");Ub=a("12");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");
$b=a("");ac=a("13");bc=a("");cc=a("14");dc=a("");ec=a("15");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("16");nc=a("");oc=a("");pc=a("17");
qc=a("18");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("19");yc=a("");zc=a("");Ac=a("20");Bc=a("");Cc=a("32");Dc=a("33");Ec=a("");Fc=a("");R=a("");Gc=a("");
Hc=a("");Ic=a("");Jc=a("");Kc=a("21");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("22");Wc=a("");Xc=a("");Yc=a("");Zc=a("");
$c=a("");ad=a("");bd=a("");cd=a("23");dd=a("");ed=a("");hd=a("24");id=a("");ld=a("");md=a("");nd=a("");od=a("25");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");
wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");
Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");
de=a("26");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");
ue=a("27");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be="";Ce=a("");De=a("28");Ee=a("");Fe=a("");Ge=a("");He=a("29");Ie=a("");Je=a("");Ke=a("");
Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("30");Re=a("31");Se=a("")})();var Te=function(){},M=function(a){return"function"==typeof a},S=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Ue=function(a){return"number"==Ca(a)&&!isNaN(a)},Ve=function(a){return/^[0-9]+$/.test(a)},We=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Xe=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},N=function(a){return Math.round(Number(a))||0},oa=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},Ye=function(a){var b=[];if(S(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},J=function(){return new Date},Ze=function(a,b){if(!Ue(a)||!Ue(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},$e=function(){this.prefix="gtm.";this.values={}};$e.prototype.set=function(a,b){this.values[this.prefix+a]=b};$e.prototype.get=function(a){return this.values[this.prefix+a]};$e.prototype.contains=function(a){return void 0!==this.get(a)};
var af=function(a,b,c){try{if(!a[$c])return a[Ac](a,b||Te,c||Te);c&&c()}catch(d){}return!1},bf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Xe(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},cf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},df=function(a){return function(){return a("GTM-MB3LRF")}},ef=function(a){for(var b=0;b<a.length;b++)a[b]()},ka=J().getTime(),na=function(a,
b,c){return a&&a.hasOwnProperty(b)?a[b]:c},ff=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},gf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},la=function(a,b,c){if(!(b&&c&&gf(a)&&S(a)&&0!=a.length))return null;for(var d={},e=0;e<a.length;e++)a[e]&&a[e].hasOwnProperty(b)&&a[e].hasOwnProperty(c)&&(d[a[e][b]]=a[e][c]);return d},hf=function(a,b){0==b?a.Na=!0:a.complete=!0;var c=a.g;a.i&&(a.i.ka[c]=b);Ja[c]&&(Ja[c].state=b)},jf=function(a,b){a.sort(function(a,
d){return b(a,d)?-1:b(d,a)?1:0})};var A=window,P=document,sf=navigator,I=function(a,b,c){var d=A[a];A[a]=void 0===d||c?b:d;return A[a]},O=function(a,b,c,d){return(d||"http:"!=A.location.protocol?a:b)+c},tf=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},pa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},p=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;pa(d,b);c&&(d.onerror=c);tf(d)},ha=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";tf(c);pa(c,b);void 0!==a&&(c.src=a);return c},C=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},T=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},q=function(a){A.setTimeout(a,0)},sa=!1,
ta=[],uf=function(a){if(!sa){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){sa=!0;for(var e=0;e<ta.length;e++)ta[e]()}}},vf=0,wf=function(){if(!sa&&140>vf){vf++;try{P.documentElement.doScroll("left"),uf()}catch(a){A.setTimeout(wf,50)}}},yf=function(a){var b=P.getElementById(a);if(b&&xf(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(xf(document.all[a][c],"id")==a)return document.all[a][c];return b},xf=function(a,
b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},zf=function(a){return a.target||a.srcElement||{}},wa=function(a){var b=P.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Af=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Bf=!1,Cf=[],
Df=function(){if(!Bf){Bf=!0;for(var a=0;a<Cf.length;a++)Cf[a]()}},Ef=function(a){a=a||A;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},ua=function(a){window.console&&window.console.log&&window.console.log(a)};var Ff=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||A.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||A.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:A.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=We(d||[],l[l.length-
1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),k=0;k<m.length;k++){var n=m[k].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Gf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},xa=function(a){var b=P.createElement("a");
a&&(b.href=a);return b};var ga=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ba=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Ff(xa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};var fa=function(a,b){p("//bat.bing.com/bat.js",a,b)},u=A,da=function(a,b,c){b&&(void 0===u[a]||c&&!u[a])&&(u[a]=b);return u[a]};var Hf=new $e,If={},Kf={set:function(a,b){Fa(Jf(a,b),If)},get:function(a){return H(a,2)},reset:function(){Hf=new $e;If={}}},H=function(a,b){if(2==b){for(var c=If,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Hf.get(a)},Jf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Lf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Mf={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Nf={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Of=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Pf=function(){var a=H("gtm.whitelist");
var b=a&&Of(Ye(a),Mf),c=H("gtm.blacklist")||H("tagTypeBlacklist")||[];Lf.test(A.location&&A.location.hostname)&&(c=Ye(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&Of(Ye(c),Nf),e={};return function(f){var g=f&&f[Ac];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>We(b,g.a))if(g.b&&0<g.b.length)for(var l=0;l<g.b.length;l++){if(0>We(b,
g.b[l])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var k;if(!(k=0<=We(d,g.a)))a:{for(var n=g.b||[],r=new $e,t=0;t<d.length;t++)r.set(d[t],!0);for(t=0;t<n.length;t++)if(r.get(n[t])){k=!0;break a}k=!1}m=k}return e[g.a]=!h||m}};var kf=function(a){var b=P;return Qf?b.querySelectorAll(a):null},Rf=!1;if(P.querySelectorAll)try{var Sf=P.querySelectorAll(":root");Sf&&1==Sf.length&&Sf[0]==P.documentElement&&(Rf=!0)}catch(a){}var Qf=Rf;var Tf=void 0,Uf="",Vf=0,Wf=void 0,_et=function(a){var b,c=H("gtm.element"),d=H("event"),e=Number(J());if(Tf===c&&Uf===d&&Vf>e-250)b=Wf;else{var f;if(c){var g=c.innerText||c.textContent||"";g&&" "!=g&&(g=g.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));g&&(g=g.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));f=g}else f="";Wf=b=f;Tf=c;Uf=d}Vf=e;return b?b:a[Xb]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(H("gtm.elementUrl")||a[Xb]||""),c=xa(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ia};_e.a="e";_e.b=["google"];var Xf=/(^|\.)doubleclick\.net$/i,Yf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Zf=function(a){for(var b=String(P.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=Xe(e[0]);if(f&&f==a){var g=Xe(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},$f=function(a,b,c,d,e){if(Xf.test(P.location.hostname)||"/"==c&&Yf.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=P.cookie;P.cookie=f;return g!=
P.cookie||0<=We(Zf(a),b)},ag=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},bg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},cg=function(){var a=Ff(A.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var dg=function(a,b){this.f=a;this.j=b};dg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var eg=function(a,b){this.za=a;this.ba=b};eg.prototype.toString=function(){return""+this.ba+"."+this.za};var hg=function(a,b){var c=new fg(null,a,b);gg(c);return c},fg=function(a,b,c){this.Ga=Math.floor(J().getTime()/864E5);this.aa=b||"auto";this.T=c||"/";var d=ag(this.aa),e=bg(this.T);this.C=a||new dg(d,e);this.h=[];this.A=new $e},jg=function(a,b,c){b&&(""==c.za?ig(a,b):(a.A.contains(b)||a.h.push(b),a.A.set(b,c)))},kg=function(a,b){for(var c=0;c<b.length;c++)jg(a,b[c][0],b[c][1])},ig=function(a,b){var c=We(a.h,b);0<=c&&a.h.splice(c,1);a.A.set(b,void 0)},lg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.A.get(d)])}return b},mg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.A.get(a.h[c]).ba);return 864E5*b};fg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.A.get(c).toString())}return"GAX1."+this.C.toString()+"."+a.join("!")};
var ng=function(a,b){for(var c=new Date,d=bg(a.T),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.A.get(g).ba<a.Ga&&e.push(g)}for(f=0;f<e.length;f++)ig(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(mg(a));if("auto"!=a.aa)return $f("_gaexp",a.toString(),a.T,a.aa,c);for(var h=cg(),l=0;l<h.length;l++)if("none"!=h[l]&&(a.C=new dg(ag(h[l]),d),$f("_gaexp",a.toString(),a.T,h[l],c)))return!0;return!1},gg=function(a){for(var b=a.C.f,c=a.C.j,d=Zf("_gaexp"),e=[],f=0;f<d.length;f++){var g=og(a,d[f]);g&&e.push(g)}jf(e,
function(a,d){var e=a.C,f=d.C;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.C=0<e.length?e[0].C:new dg(b,c);for(f=e.length-1;0<=f;f--)kg(a,lg(e[f]))},og=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Xe(e[0]);if(0!=f.length){var g=2==e.length?Xe(e[1]):"1";if(Ve(f)&&Ve(g)){d=new dg(N(f),N(g));
break a}}}d=void 0}if(d){for(var h=new fg(d,a.aa,a.T),l=(c[2]||"").split("!"),m=0;m<l.length;m++){var k=l[m].split(".");if(3==k.length){if(!Ve(k[1]))return;jg(h,k[0],new eg(k[2],N(k[1])))}}return h}}};var _v=function(a){var b=H(a[hd].replace(/\\\./g,"."),a[Pb]);return void 0!==b?b:a[Xb]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(H("gtm.referrer")||P.referrer);if(!b)return b;var c=xa(b);return b};_f.a="f";_f.b=["google"];var ja=function(a){var b=A.location,c;(c=a[Mb]?a[Mb]:H("gtm.url"))&&(b=xa(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[wb]&&(f=Ff(b,a[wb],a[Yd],a[Wb],a[Ld]));return f},_u=ja;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[Xa]).indexOf(String(a[Q]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[Xa])==String(a[Q])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[Q],a[Gc]?"i":void 0)).test(a[Xa])};_re.a="re";_re.b=["google"];var Cg=Math.random(),Dg="1.000000">Cg;var Eg=Te;var Fg=Te,Gg=[],Hg=!1,Ig=function(a){return A["dataLayer"].push(a)},Jg=function(a){var b=!1;return function(){!b&&M(a)&&q(df(a));b=!0}},Pg=function(){for(var a=!1;!Hg&&0<Gg.length;){Hg=!0;var b=Gg.shift();if(M(b))try{b.call(Kf)}catch(Ta){}else if(S(b))a:{var c=b;if("string"==Ca(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=If,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Ta){}}}else{var l=b,m=void 0;for(m in l)if(l.hasOwnProperty(m)){var k=m,n=
l[m];Hf.set(k,n);Fa(Jf(k,n),If)}var r=!1,t=l.event,v=void 0;if(t){v=ka++;Ia=t;if(!l["gtm.uniqueEventId"]){var x=v;Hf.set("gtm.uniqueEventId",x);Fa(Jf("gtm.uniqueEventId",x),If)}var z=Jg(l.eventCallback),D=l.eventTimeout;D&&A.setTimeout(z,Number(D));r=Fg(v,t,z,l.eventReporter)}Ha||(Ha=l["gtm.start"])&&Eg();var E=l,F=v,y=t,B=If;if(!r){var G=v,K=t;}Ia=null;a=r||a}var X=b,L=If;Og();Hg=!1}return!a};var Qg,Rg,Sg,Tg=/(Firefox\D28\D)/g.test(sf.userAgent),Zg=function(a,b){return function(c){c=c||A.event;var d=zf(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Af(d,["a","area"]),e=!d||!d.href||Ug(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Sg:Rg;if(c.defaultPrevented||!1===c.returnValue||c.oa&&c.oa()){if(d){var g={simulateDefault:!1},h=Vg(f,["wnc","nwnc"]);h&&Wg(a,d,g,f.wt,h)}}else{if(d){var g={},l=!0,m=Vg(f,
["wnc","nwnc","nwc","wc"]);(l=Wg(a,d,g,f.wt,m))||(Xg(g.eventReport,f)?b=!0:e=!0);e=e||l||"LINK_CLICK"==a&&Tg;g.simulateDefault=!l&&b&&!e;g.simulateDefault&&(e=Yg(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=l||!b||e;return c.returnValue}return!0}}}},Wg=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||xf(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=$g(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=ah(b);g.eventTimeout=f;g.eventCallback=bh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return Ig(g)},
ah=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},ch=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Yg=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(sf.userAgent),e=ch(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=A.frames&&A.frames[f]||A[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+J().getTime(),b.targetWindow=A.open("",b.targetWindowName));break;default:d&&!A.frames[e]?(b.simulateDefault=!1,c=!0):(A.frames[e]||(b.targetWindowName=e),b.targetWindow=A.frames[e]||A.open("",e))}return c},$g=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||J().getTime(),500>J().getTime()-c&&A.setTimeout($g(a,b,c),25)))}},bh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;dh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||J().getTime(),500>J().getTime()-c&&A.setTimeout(bh(a,b,c),25)}},Vg=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},eh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Xg=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<fh.length;c++)if(a.passingRules[c]){var d=fh[c],e=gh[c],f=e&&e[0]&&e[0][0]||e[1]&&e[1][0];if(f&&"0"!=f&&(b.wc[f]||b.wnc[f]))for(var g=d[1],h=0;h<g.length;h++)if(a.resolvedTags[g[h]])return!0}return!1},hh=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=zf(a);b&&Wg("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Qg&&(Qg=Gf(P.location));eh(Rg,b||!1,c||!1,d,e);if(P.gtmHasLinkClickListenerTag)return;
P.gtmHasLinkClickListenerTag=!0;f="click";g=Zg(a,b||!1);break;case "FORM_SUBMIT":eh(Sg,b||!1,c||!1,d,e);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";g=Zg(a,b||!1);break;default:return}T(P,f,g,h)},Ug=function(a){if(!Qg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=xa(a);return Qg==Gf(c)},dh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit};var pg=new String("undefined"),ph=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===pg?b:a[d]);return c.join("")}};ph.prototype.toString=function(){return this.resolve("undefined")};ph.prototype.valueOf=ph.prototype.toString;var qh={},rh=function(a,b){var c=ka++;qh[c]=[a,b];return c},sh=function(a){var b=a?0:1;return function(a){var d=qh[a];if(d&&M(d[b]))d[b]();qh[a]=void 0}};var th=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},uh=function(a,b){return a<b?-1:a>b?1:0};var vh;a:{var wh=ya.navigator;if(wh){var xh=wh.userAgent;if(xh){vh=xh;break a}}vh=""}var V=function(a){return-1!=vh.indexOf(a)};var yh=V("Opera"),zh=V("Trident")||V("MSIE"),Ah=V("Edge"),Bh;if(Bh=V("Gecko"))Bh=!(-1!=vh.toLowerCase().indexOf("webkit")&&!V("Edge"));var Ch=Bh&&!(V("Trident")||V("MSIE"))&&!V("Edge"),Dh=-1!=vh.toLowerCase().indexOf("webkit")&&!V("Edge");Dh&&V("Mobile");V("Macintosh");V("Windows");V("Linux")||V("CrOS");var Eh=ya.navigator||null;Eh&&(Eh.appVersion||"").indexOf("X11");V("Android");!V("iPhone")||V("iPod")||V("iPad");V("iPad");V("iPod");
var Fh=function(){var a=ya.document;return a?a.documentMode:void 0},Gh;a:{var Hh="",Ih=function(){var a=vh;if(Ch)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ah)return/Edge\/([\d\.]+)/.exec(a);if(zh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Dh)return/WebKit\/(\S+)/.exec(a);if(yh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ih&&(Hh=Ih?Ih[1]:"");if(zh){var Jh=Fh();if(null!=Jh&&Jh>parseFloat(Hh)){Gh=String(Jh);break a}}Gh=Hh}
var Kh=Gh,Lh={},Mh=function(a){var b;if(!(b=Lh[a])){for(var c=0,d=th(String(Kh)).split("."),e=th(String(a)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var n=m.exec(h)||["","",""],r=k.exec(l)||["","",""];if(0==n[0].length&&0==r[0].length)break;c=uh(0==n[1].length?0:parseInt(n[1],10),0==r[1].length?0:parseInt(r[1],10))||uh(0==n[2].length,0==r[2].length)||uh(n[2],r[2])}while(0==c)}b=Lh[a]=0<=c}return b},
Nh=ya.document,Oh=Nh&&zh?Fh()||("CSS1Compat"==Nh.compatMode?parseInt(Kh,10):5):void 0;var Ph;if(!(Ph=!Ch&&!zh)){var Qh;if(Qh=zh)Qh=9<=Number(Oh);Ph=Qh}Ph||Ch&&Mh("1.9.1");zh&&Mh("9");var Rh=function(a){Rh[" "](a);return a};Rh[" "]=function(){};var va=function(a,b){var c="";zh&&!Sh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Th)a.srcdoc=d;else if(Uh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Vh(a,d)},Th=Dh&&"srcdoc"in document.createElement("iframe"),Uh=Ch||Dh||zh&&Mh(11),Vh=function(a,b){zh&&Mh(7)&&!Mh(10)&&6>Wh()&&Xh(b)&&(b=Yh(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};zh&&!Sh(a)?Zh(a,c):c()},Wh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Sh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Rh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},$h=0,Zh=function(a,b){var c="goog_rendering_callback"+$h++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Xh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Yh=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var pi=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=mi(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var l=ni(a+"{"+e+"}",f);oi(l,f);var m=l.parentNode;return function(){m.removeChild(l)}},qi=null,mi=function(a){if(qi)return qi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return qi=c}0==a.styleSheets.length&&
a.createStyleSheet();return qi=a.styleSheets[0]},ni=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},oi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var xi={},W=void 0,yi=function(a){var b=xi[a];b||(b={id:a,s:[],O:0,Ba:null,ua:void 0,ya:!1},xi[a]=b);W=b},Ai=function(a,b,c,d){var e=W;if(!Qf||!e)return!1;var f={id:e.id+":"+e.s.length,Va:b,M:[],Qa:c,D:a,ma:0,ja:d||null,Fa:0,N:!1};e.s.push(f);null===a?(f.N=!0,b(null)):zi(e);return!0},Bi=function(a){var b=pi(a,"visibility","hidden",!0);return function(){M(b)&&b.apply();b=null}},Ci=function(a,b,c,d){var e=b;if(!sa){var f=Bi(a.v);ta.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Ai(a,e,c,
d)},zi=function(a){if(!a.ya){for(var b=a.O;b<a.s.length;b++){var c=a.s[b],d=b==a.O;if(!c.N&&!Di(d,c))break;c.N&&d&&a.O++}a.s.length>a.O?(a.Ba||(a.Ba=A.setTimeout(function(){a.Ba=null;zi(a)},80)),sa||a.ua||(a.ua=function(){q(function(){zi(a)})},T(P,"DOMContentLoaded",a.ua))):Ei(a)}},Ei=function(a){for(var b=0;b<a.s.length;b++){var c=a.s[b];if(c.D)for(var d=kf(c.D.v)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Fi(f,c.id),c.M.push(Gi(f,c.id)))}}},Di=function(a,
b){var c=[];if(b.D){var d=Hi(b.D,b.id),e=null;b.ja&&(e=Hi(b.ja,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!sa&&(null===b.ja.o||b.Fa+c.length<b.ja.o)))break;c.push({element:g,vb:h})}}if(!sa&&b.Qa&&(!a||null==b.D.o||b.D.o!=b.ma+c.length))return!1;for(var l=0;l<c.length;l++){var m=c[l].element,k=c[l].vb,n;b.ma++;Fi(m,b.id);k&&(b.Fa++,n=b.id+"-t",Fi(k,n));var r=b.Va(m,k);M(r)&&b.M.push(r);b.M.push(Gi(m,b.id));k&&n&&b.M.push(Gi(k,n))}if(b.D.o&&b.D.o==b.ma||
sa)b.N=!0;return!0},Fi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Gi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Hi=function(a,b){for(var c=kf(a.v)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.B&&!Ii(f))break;d.push(f)}}return d},Ii=function(a){if(sa)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Li,Mi;var Wi=function(a){return function(){}},Xi=function(a){return function(){}};var xj=function(a){var b=A||ya,c=b.onerror,d=!1;Dh&&!Mh("535.3")&&(d=!d);b.onerror=function(b,f,g,h,l){c&&c(b,f,g,h,l);a({message:b,fileName:f,ob:g,Lb:h,error:l});return d}};
var yj=function(a){var b=function(b){b=b||A.event;var d=a.call(this,b);b.returnValue=!1!==d&&(b.returnValue||void 0===b.returnValue);return d};b.gtmOnclickWrapper=!0;return b},_lcl=function(a,b){var c=na(a,Qe,!0),d=na(a,rb,!0),e=N(a[Re]);0>=e&&(e=2E3);var f=na(a,De,"");hh("LINK_CLICK",!!c,!!d,e,String(f));if(!P.gtmLinkClickListener&&(P.gtmLinkClickListener=!0,!P.addEventListener)){var g=function(a){a=a||A.event;for(var b=zf(a);b;)b.onclick&&!b.onclick.gtmOnclickWrapper&&(b.onclick=yj(b.onclick)),
b=b.parentElement};T(P,"mousedown",g,!1);T(P,"keydown",function(a){a=a||A.event;13==a.keyCode&&g(a)},!1)}q(b)};_lcl.a="lcl";_lcl.b=[];var Tj=86,Uj=[],Vj=[],Wj=[],Xj=new $e,Yj=[],Z=[],fh=[],gh=[],Zj=function(){this.G=[]};Zj.prototype.set=function(a,b){this.G.push([a,b]);return this};Zj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.G.length;d++){var e=ak(this.G[d][0],a,b),f=ak(this.G[d][1],a,b);c[e]=f}return c};var bk=function(a){this.index=a};bk.prototype.resolve=function(a,b){var c=Wj[this.index];if(c&&!b(c)){var d=c[Kc];if(a){if(a.get(d))return;a.set(d,!0)}c=ak(c,a,b);a&&a.set(d,!1);return af(c)}};
var _M=function(a){return new bk(a)},ck=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=ak(Uj[a[f]],b,c);g===pg&&(e=!0);d.push(g)}return e?new ph(d):d.join("")}},_T=function(a){return new ck(arguments)},dk=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=
function(c,d){var e=ak(a[0],c,d);if(a[0]instanceof bk&&b(8)&&b(16)){if(e===pg)return e;var f="gtm"+ka++;Xj.set(f,e);return'google_tag_manager["GTM-MB3LRF"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new dk(arguments)},ek=function(a,b){this.u=a;this.ia=b},_R=function(a,b){return new ek(a,b)},fk=function(a,b){return ak(a,new $e,b)},ak=function(a,b,c){var d=a;if(a instanceof bk||a instanceof Zj||a instanceof ck||a instanceof dk)return a.resolve(b,
c);if(!(a instanceof ek))if(S(a))for(var d=[],e=0;e<a.length;e++)d[e]=ak(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=ak(a[f],b,c))}return d},gk=function(a,b){var c=b[a],d=c;if(c instanceof bk||c instanceof dk||c instanceof ck||c instanceof ek)d=c;else if(S(c))for(var d=[],e=0;e<c.length;e++)d[e]=gk(c[e],b);else if("object"==typeof c){var d=new Zj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],gk(c[f],b))}return d},ik=function(a,b){for(var c=b?b.split(","):
[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=Uj[e[1]]);if(1==a)for(var f=hk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Vj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=hk(e[g]);3==a&&(c[d]=Uj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var l=0;l<e[g].length;l++)e[g][l]=Uj[e[g][l]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},hk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Tj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f=0,f=65<e&&90>=
e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},jk=function(a,b,c){a.push.apply(a,ik(b,c))};
var Lg=function(){},rk=function(a){},Og=function(){},sk=function(a){},tk=function(a,b){},uk=function(a,b){},Mg=function(a){};var vk=function(a){var b=this;this.g=a;this.complete=this.Na=!1;this.ha=[];this.ca=[];this.S=function(){if(b.i&&b.i.event){var a=b.i.event,d=b.g;}b.complete||ef(b.ha);hf(b,1)};this.R=function(){if(b.i&&b.i.event){var a=b.i.event,d=b.g;}b.complete||ef(b.ca);hf(b,2)};this.w=Te},wk=function(a,b){a.ha.push(b)},
xk=function(a,b){a.ca.push(b)},yk=function(a){this.H=[];this.Aa=[];this.Ha={};this.sa=[];this.P=0;this.La={};this.Oa={};this.ka={};this.event=a};yk.prototype.addListener=function(a){this.sa.push(a)};
var zk=function(a,b,c,d,e,f){if(!c.complete){a.H[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=S(d)?d.slice():["or",d];e=S(e)?e.slice():[e];f=S(f)?f.slice():[f];a.Ha[b]=d;a.La[b]=0<e.length;a.Oa[b]=0<f.length;a.P++;var g=function(){0<a.P&&a.P--;0<a.P||ef(a.sa)};wk(c,g);xk(c,g)}},Ak=function(a,b,c){a.H[b]&&(wk(a.H[b],function(){c(b,!0)}),xk(a.H[b],function(){c(b,!1)}))},Bk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof ek&&a[g].u===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Fk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Ck(h,b,a);if(f=g){var k=Dk(b,!0);0<k.length&&e(k[0].u);c.push(f);var l=Dk(b,!1);0<l.length&&e(l[0].u)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Dk(g.g,!0);if(0<h.length){var l=c[f-1],m=Ek(g);wk(l,m);0==h[0].ia&&xk(l,m)}var k=Dk(g.g,!1);0<k.length&&(m=Ek(c[f+1]),wk(g,m),0==k[0].ia&&xk(g,m))}a.Aa.push(c)}},Dk=function(a,b){var c=b?Vd:le,d=Z[a],e=void 0===d[c]?[]:d[c];return S(e)?e:[e]},Ek=function(a){return function(){a.w()}},Hk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Dk(a,!0);0<b.length&&f(b[0].u);e.push(a);var c=Dk(a,!1);0<c.length&&f(c[0].u)};
f(d.g);b[d.g]=e}Gk(a,b);return b},Gk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<We(b[e],d)){delete b[d];break}}};var Jk=function(a,b){return function(){a[Cc]=b.S;a[Dc]=b.R;var c=b.g,d=b.i&&b.i.ka[c],e=Ja[c]&&Ja[c].state,f=d?void 0!==d:b.Na,g=Ja[c]&&Ja[c].firingOption,h=g&&2==g,l=g&&1==g;if((f||e&&0!=e)&&(f||h)&&(h||l))h&&Ja[c]&&1==Ja[c].state||l&&b.i&&1==b.i.ka[c]?b.S():b.R();else{var m=b.i?b.i.event:void 0;a=Ik(a,m?m.c:Pf());hf(b,0);if(m){var k=a;tk(m,c)}af(a,b.S,b.R)}}},Ik=function(a,b){a=fk(a,b);return a},Ck=function(a,b,c){var d=new vk(b);d.i=c;wk(d,Wi(a));xk(d,Xi(a));d.w=Jk(a,d);return d};
var Nk=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];A[m()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!ma(b))return!1;for(var e=na(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[ec]?c=H("ecommerce"):
a[dc]&&(c=a[dc].ecommerce);if(!ma(c))return;c=Object(c);var e=na(a[xc],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function l(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&v[e]||!c&&void 0===v[e])){var f=x[e]?oa(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}I("GoogleAnalyticsObject",a[hd]||"ga",!1);var m=function(){return A.GoogleAnalyticsObject},k=I(m(),function(){var a=A[m()];a.q=a.q||[];a.q.push(arguments)},!1);k.l=Number(J());var n="",r="";void 0==a[ye]?(r="gtm"+ka++,n=r+"."):""!==
a[ye]&&(r=a[ye],n=r+".");var t=!1;var v={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0},x={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useBeacon:!0};
var z={name:r};void 0!==
a[Ua]&&(z.allowLinker=a[Ua]);l(a[xc],z,!0);k("create",a[La],z);d("set","&gtm","GTM-MB3LRF");void 0!==a[Va]&&d("set","anonymizeIp",a[Va]||void 0);e("nonInteraction",od);g("contentGroup",a[xb]);g("dimension",a[ac]);g("metric",a[cd]);
var D={};l(a[xc],D,!1)&&d("set",D);a[Vc]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(M(a[Ec]))a[Ec]();else{var c=a[xc],d=c&&c.hitCallback;M(d)&&d()}b()});
if(a[ue]){a[lc]&&(d("require","ec","ec.js"),h()),d("send",{hitType:"event",eventCategory:String(a[qc]),eventAction:String(a[pc]),eventLabel:f(String,a[rc]),eventValue:f(N,a[sc])});}else if(a[ve]){}else if(a[xe]){}else if(a[we]){}else if(a[Vb]){}else if(a[Tb]){}else if(a[te]){}else{a[lc]&&(d("require","ec","ec.js"),h());if(a[cc]&&!a[oc]){var K="_dc_gtm_"+String(a[La]).replace(/[^A-Za-z0-9-]/g,
"");d("require","displayfeatures",void 0,{cookieName:K})}d("send","pageview");if(a[Za]){d("require","linker");var X=String(a[Za]).replace(/\s+/g,
"").split(",");k(n+"linker:autoLink",X,a[He],a[Ub])}}if(!Nk){var L=a[Rb]?"u/analytics_debug.js":"analytics.js";a[Lc]&&!a[Rb]&&(L="internal/"+L);Nk=!0;p(O("https:","http:","//www.google-analytics.com/"+L,t),function(){A[m()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Ok,Pk;var Yk=!1;var Zk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Yj[b]&&fk(Yj[b],c),e=d;if(d)if(d[Wa]&&S(d[Q]))for(var f=d[Q],e=!1,g=0;!e&&g<f.length;g++)d[Q]=f[g],e=af(d);else e=af(d);a[b]=[e,d]}return a[b]}},qk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.K(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.K(e[d],a.c)[0])return!1;return!0},$k=!1,Fg=function(a,b,c,d){switch(b){case "gtm.js":if($k)return!1;$k=!0;break;case "gtm.sync":if(H("gtm.snippet")!=Ga)return!1}H("tagTypeBlacklist");
for(var e={id:a,name:b,Y:c||Te,X:hk(),ga:hk(),K:Zk(),c:Pf()},f=[],g=0;g<fh.length;g++)if(qk(e,fh[g])){f[g]=!0;for(var h=e,l=fh[g],m=l[1],k=0;k<m.length;k++)h.X[m[k]]=!0;for(var n=l[3],k=0;k<n.length;k++)h.ga[n[k]]=!0}else f[g]=!1;tk(e);var t=[];for(var v=0;v<Tj;v++)if(e.X[v]&&!e.ga[v])if(e.c(Z[v])){}else{t[v]=Z[v];}e.L=t;for(var x=new yk(e),z=0;z<Tj;z++)if(e.X[z]&&!e.ga[z])if(e.c(Z[z])){}else{var D=e.L[z],E=Ck(D,z,x);zk(x,z,E,D[Yb],D[Vd],D[le]);if(D[Ka])break}x.addListener(e.Y);for(var F=[],y=
0;y<x.H.length;y++){var B=x.H[y];if(B){var w=x.Ha[y],G=x.La[y],K=x.Oa[y];if(0!=w.length||G||K){if(0<w.length)for(var X=Bk(w,B.w),L=0;L<w.length;L++)w[L]instanceof ek&&w[L].u!=y&&Ak(x,w[L].u,X);(G||K)&&Fk(x,y)}else F.push(y)}}for(y=0;y<F.length;y++)x.H[F[y]].w();for(y=0;y<x.Aa.length;y++){for(var Ta=x.Aa[y],aa=Ta,ea=[],ca=0;ca<aa.length;ca++){var kb=aa[ca],ib=kb.g,Eb=Ja[ib],jd=Eb.firingOption;0!=jd&&(1==jd&&void 0!==kb.i.ka[ib]||2==jd&&void 0!==Eb.state)&&ea.push(kb)}var kd=Hk(ea),mc=void 0;for(mc in kd)if(kd.hasOwnProperty(mc)){for(var lf=
void 0,ij=void 0,fd=kd[mc],ml=fd[0],jj=fd[fd.length-1],kj,Ea=0;Ea<aa.length;Ea++){var gd=aa[Ea];!lf&&gd.g==ml&&0<Ea&&(lf=aa[Ea-1]);gd.g==jj&&Ea<aa.length-1&&(ij=aa[Ea+1]);if(-1<We(fd,gd.g))if(kj=aa.splice(Ea,1)[0],gd.g==jj)break;else Ea--}if(kj){var lj=Number(mc),ia=lf,mf=ij;if(ia){var nl=ia.ha[0],ol=ia.ca[0],mj=ia;mj.ha=[];mj.ca=[];wk(ia,nl);xk(ia,ol)}if(ia&&mf){var nf=Ek(mf);wk(ia,nf);var of=Dk(ia.g,!1);0<of.length&&of[0].u!=lj&&0==of[0].ia&&xk(ia,nf);var pf=Dk(mf.g,!0);0<pf.length&&pf[0].u!=lj&&
0==pf[0].ia&&xk(ia,nf)}}}0<Ta.length&&Ta[0].w()}0<x.P||ef(x.sa);d&&M(d)&&d({passingRules:f,
resolvedTags:e.L});if("gtm.js"==b||"gtm.sync"==b)a:{}for(var pj in e.L)if(e.L.hasOwnProperty(pj)){var qj=e.L[pj],qf;if(!(qf=void 0==qj[Kc])){var rj=qj[Kc];qf=!("function"!=typeof String.prototype.startsWith?0===rj.indexOf("_implicit"):rj.startsWith("_implicit"))}if(qf)return!0}return!1};var al={macro:function(a){if(Xj.contains(a))return Xj.get(a)}};al.dataLayer=Kf;al.onHtmlSuccess=sh(!0);al.onHtmlFailure=sh(!1);al.Za=function(){var a=A.google_tag_manager;a||(a=A.google_tag_manager={});a["GTM-MB3LRF"]||(a["GTM-MB3LRF"]=al);qa=a};(function(){var a=function(a){var c=I("google_tag_manager",{},!1),d=c[a];d||(d=c[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Rg=a("linkClickMap");Sg=a("formSubmitMap")})();
Uj.push.apply(Uj,function(){for(var a=[_re,_u,'url',_M(0),'.*',_eq,_e,'_event',_M(1),'gtm.js','',_ua,'UA-51917484-1',false,{},'udacity.com','\x26tid','\x26aip',{16:12,17:13},true,3,_cn,'https://developers.google.com/web/','UA-52746336-1',{16:23,17:13},4,'https://developers.google.com/','UA-24532603-1',{16:27,17:13},1,_v,'element url','gtm.elementUrl',_M(2),'https://github.com/google/web-starter-kit/releases/','event',_M(3),'gtm.linkClick','Web Starter Kit Download','\x26t','\x26ec','\x26ea','\x26ni',{16:27,39:35,40:38,41:33,17:13,42:13},7,{16:23,39:35,40:38,41:33,17:13,42:13},6,_lcl,'0','2000',5,'url path','path',_f,'referrer','url hostname','host','history change source','gtm.historyChangeSource','history old state','gtm.oldHistoryState','history new state','gtm.newHistoryState','history old url fragment','gtm.oldUrlFragment','history new url fragment','gtm.newUrlFragment',_et,'element text','element target','gtm.elementTarget','element id','gtm.elementId','element classes','gtm.elementClasses','element','gtm.element'],b=[],c=0;c<a.length;c++)b[c]=gk(c,a);return b}());jk(Vj,0,"20:0,20:1,21:2,5:3,6:4,20:5,20:6,21:7,5:8,6:9,20:11,0:12,16:13,15:13,4:13,10:14,13:14,23:14,29:13,19:14,11:13,7:15,12:13,2:18,22:13,1:13,14:19,26:20,20:21,6:22,0:23,2:24,26:25,6:26,0:27,2:28,26:29,20:30,21:31,24:32,5:33,6:34,21:35,5:36,6:37,27:19,3:19,18:38,17:33,25:13,2:43,26:44,2:45,26:46,20:47,30:19,8:19,28:48,31:49,26:50,21:51,9:52,20:53,21:54,21:55,9:56,21:57,24:58,21:59,24:60,21:61,24:62,21:63,24:64,21:65,24:66,20:67,21:68,21:69,24:70,21:71,24:72,21:73,24:74,21:75,24:76");jk(Wj,1,"G,AD,AAAAAAO,ABAAAAAB,CAAAAAAAAAD,AAAAAAAAAAM,CAAAAAAAAAw,AAAAAACAAAAD,AAAAAACAAAAM,AAAAAACAAAAw,AAAAAACAAAAAD,AAAAAACAAAAAM,AAAAAAAAAAAAw,AAAAAACAAAAAAD,AAAAAACAAAAAAM,AAAAAACAAAAAAw,AAAAAACAAAAAAAD");jk(Yj,1,"Z,gM,IAAAw,IAAAQI,AAAAQAw,AAAAQAAG");jk(Z,1,"Aw__P,AQ_XDH,AQ_XDwB,AQ_GBQA4P,AQ_GBBA4z,AAAAAAAAA_");jk(fh,2,"D:h::,G:C::,K:E::,w:Y::");jk(gh,4,"10.10:,10:,10:,10.10:");for(var bl=0;bl<Z.length;bl++){var cl=Z[bl],dl=1;cl[qd]?dl=2:cl[Ee]&&(dl=0);Ja[bl]={firingOption:dl,state:void 0}}al.Za();
(function(a){})("async");
(function(){var a=I("dataLayer",[],!1),b=I("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};ta.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Cf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Gg.push.apply(Gg,b);300<this.length;)this.shift();return Pg()};Gg.push.apply(Gg,a.slice(0));q(Pg)})();
if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)uf();else{T(P,"DOMContentLoaded",uf);T(P,"readystatechange",uf);if(P.createEventObject&&P.documentElement.doScroll){var ll=!0;try{ll=!A.frameElement}catch(a){}ll&&wf()}T(A,"load",uf)}"complete"===P.readyState?Df():T(A,"load",Df);
(function(a){})("async");(function(){})();var _vs="res_ts:1410257384101000,srv_cl:121885630,ds:live,cv:16";
})()
